<a href="https://colab.research.google.com/github/ganeshdasrla/odin_python/blob/main/Python_Class_on_April_20th_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
abc = lambda n1,n2,n3: n1*n2*n3
print(abc(3,4,5))

60


In [4]:
# map(function, iterable)
numbers = [1, 2, 3, 4, 5]
squared_numbers = list(map(lambda x:x*x, numbers))

In [7]:
a=[2,3,5,7,9]
sq=lambda x: x*x
list(map(sq,a))

[4, 9, 25, 49, 81]

In [8]:
list(map(lambda x: x*x, a))

[4, 9, 25, 49, 81]

In [10]:
a=['welcome', 'hi', 'python']
list(map(lambda x: len(x), a))

[7, 2, 6]

In [13]:
def getLength(a):
  count=0
  for char in a:
    count += 1
  return count
getLength('abcd heloo')

10

In [15]:
list(map(getLength, ["hello", "welcome", "greeting"]))

[5, 7, 8]

In [17]:
# filter(function, iterable)
a=[1,2,3,4,5,6,7,8,9]
print(list(map(lambda x:x%2==0, a)))
print(list(filter(lambda x:x%2==0,a)))

[False, True, False, True, False, True, False, True, False]
[2, 4, 6, 8]


In [19]:
list(filter(lambda x:x>5,a))

[6, 7, 8, 9]

In [21]:
#reduce(function, iterable[, initializer])
from functools import reduce

def add(x, y):
    return x + y

numbers = [1, 2, 3, 4, 5]
sum_of_numbers = reduce(add, numbers)
print(sum_of_numbers)

15


In [24]:
numbers = [1, 2, 3, 4, 5]
reduce(lambda x, y: x * y, numbers)

120

In [26]:
s=['apple', 'banana', 'watermelon']
reduce(lambda x,y: x if len(x)>len(y) else y, s)

'apple'

In [34]:
result = reduce(lambda x,y: x if len(x)>len(y) else y, s)
print(result)

watermelon


In [40]:
a=[1,2,3,4]
a*3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [45]:
#Numpy --> Numeric (or Numerical) Python
import numpy as np
a=[1,2,3,4,5]
a_r=np.array(a)
print(a_r)
print(type(a_r))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [54]:
arr=np.array([1,2,3,4,5])
print(arr**2)
arrb=np.array([5,6,7,8,6])
print(arr+arrb)
print(arr*arrb)

[ 1  4  9 16 25]
[ 6  8 10 12 11]
[ 5 12 21 32 30]


In [61]:
arr2d = np.array([[1,2,3],[4,5,6]])
print(arr2d**2)
print(type(arr2d))
print(len(arr2d))

[[ 1  4  9]
 [16 25 36]]
<class 'numpy.ndarray'>
2


In [71]:
a=[[1,2,3],
   [3,4,5],
   [4,5,6]]
arr = np.array(a)
print(arr.shape)
print(arr.ndim)
print(len(arr))

(3, 3)
2
3


In [76]:
threed = [[[1,2,3],
          [4,5,6],
          [7,8,9]],
          [[10,11,12],
           [13,14,15],
           [16,17,18]]]

arr = np.array(threed)
print(arr)
print(arr.shape)
print(arr.ndim)
print(len(arr))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
(2, 3, 3)
3
2


In [83]:
one_r = np.array([1,2,3,4,5,6])
one_r[1:4]

array([2, 3, 4])

In [78]:
one_r[3]

4

In [84]:
one_r[one_r>3]

array([4, 5, 6])

In [88]:
two_r = np.array([[1, 2, 3],
                  [4, 5, 6]])
two_r[1][1]

5

In [98]:
print(two_r[0, 1:])
print(two_r[1, 1:])

[2 3]
[5 6]


In [101]:
three_r = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]]])
three_r[0][2][1]

8

In [107]:
three_r[0, 0:2, 1:]

array([[2, 3],
       [5, 6]])